### ISSUE TITLE
Trie: Predict

### ISSUE THREAD

**Issue by vivekreddynv** [xorz57/OpenDS#129]
**Function Signature**:

vector<std::basic_string<T>> predict(const std::basic_string<T> &key);

**Notes**
1.  Returns all the words which have the prefix stating with the argument.
2.  An Empty Vector if no word has the given prefix.

**Potential Enhancement**
1. Can Use Multi-threading. Set up a Thread Pool with a fixed number of threads, which are called on various subtrees. User can control whether or not to use Multi-Threading. 

Please let me know if this sounds good.

**Comment by xorz57** [comment]
It sounds good, yes!
